//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS2812b.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Anzahl_LED {
            get {
                return ((int)(this["Anzahl_LED"]));
            }
            set {
                this["Anzahl_LED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Arduino_PIN {
            get {
                return ((int)(this["Arduino_PIN"]));
            }
            set {
                this["Arduino_PIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Com_Port {
            get {
                return ((int)(this["Com_Port"]));
            }
            set {
                this["Com_Port"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Static - No blinking. Just plain old static light.")]
        public string Modus_00 {
            get {
                return ((string)(this["Modus_00"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blink - Normal blinking. 50% on/off time.")]
        public string Modus_01 {
            get {
                return ((string)(this["Modus_01"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Breath - Does the \"standby-breathing\" of well known i-Devices. Fixed Speed.")]
        public string Modus_02 {
            get {
                return ((string)(this["Modus_02"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Color Wipe - Lights all LEDs after each other up. Then turns them in that order o" +
            "ff. Repeat.")]
        public string Modus_03 {
            get {
                return ((string)(this["Modus_03"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Color Wipe Inverse - Same as Color Wipe, except swaps on/off colors.")]
        public string Modus_04 {
            get {
                return ((string)(this["Modus_04"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Color Wipe Reverse - Lights all LEDs after each other up. Then turns them in reve" +
            "rse order off. Repeat.")]
        public string Modus_05 {
            get {
                return ((string)(this["Modus_05"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Color Wipe Reverse Inverse - Same as Color Wipe Reverse, except swaps on/off colo" +
            "rs.")]
        public string Modus_06 {
            get {
                return ((string)(this["Modus_06"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Color Wipe Random - Turns all LEDs after each other to a random color. Then start" +
            "s over with another color.")]
        public string Modus_07 {
            get {
                return ((string)(this["Modus_07"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Random Color - Lights all LEDs in one random color up. Then switches them to the " +
            "next random color.")]
        public string Modus_08 {
            get {
                return ((string)(this["Modus_08"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Single Dynamic - Lights every LED in a random color. Changes one random LED after" +
            " the other to a random color.")]
        public string Modus_09 {
            get {
                return ((string)(this["Modus_09"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Multi Dynamic - Lights every LED in a random color. Changes all LED at the same t" +
            "ime to new random colors.")]
        public string Modus_10 {
            get {
                return ((string)(this["Modus_10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rainbow - Cycles all LEDs at once through a rainbow.")]
        public string Modus_11 {
            get {
                return ((string)(this["Modus_11"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg00von {
            get {
                return ((string)(this["Seg00von"]));
            }
            set {
                this["Seg00von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg00bis {
            get {
                return ((string)(this["Seg00bis"]));
            }
            set {
                this["Seg00bis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg01von {
            get {
                return ((string)(this["Seg01von"]));
            }
            set {
                this["Seg01von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg02von {
            get {
                return ((string)(this["Seg02von"]));
            }
            set {
                this["Seg02von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg03von {
            get {
                return ((string)(this["Seg03von"]));
            }
            set {
                this["Seg03von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg04von {
            get {
                return ((string)(this["Seg04von"]));
            }
            set {
                this["Seg04von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg05von {
            get {
                return ((string)(this["Seg05von"]));
            }
            set {
                this["Seg05von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg06von {
            get {
                return ((string)(this["Seg06von"]));
            }
            set {
                this["Seg06von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg07von {
            get {
                return ((string)(this["Seg07von"]));
            }
            set {
                this["Seg07von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg08von {
            get {
                return ((string)(this["Seg08von"]));
            }
            set {
                this["Seg08von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg09von {
            get {
                return ((string)(this["Seg09von"]));
            }
            set {
                this["Seg09von"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg01bis {
            get {
                return ((string)(this["Seg01bis"]));
            }
            set {
                this["Seg01bis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg02bis {
            get {
                return ((string)(this["Seg02bis"]));
            }
            set {
                this["Seg02bis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg03bis {
            get {
                return ((string)(this["Seg03bis"]));
            }
            set {
                this["Seg03bis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg04bis {
            get {
                return ((string)(this["Seg04bis"]));
            }
            set {
                this["Seg04bis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg05bis {
            get {
                return ((string)(this["Seg05bis"]));
            }
            set {
                this["Seg05bis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg06bis {
            get {
                return ((string)(this["Seg06bis"]));
            }
            set {
                this["Seg06bis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg07bis {
            get {
                return ((string)(this["Seg07bis"]));
            }
            set {
                this["Seg07bis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg08bis {
            get {
                return ((string)(this["Seg08bis"]));
            }
            set {
                this["Seg08bis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Seg09bis {
            get {
                return ((string)(this["Seg09bis"]));
            }
            set {
                this["Seg09bis"] = value;
            }
        }
    }
}
